service: "%SERVICE_NAME%"
runtime: python27
api_version: 1
threadsafe: true
env: flex

handlers:
    - url: /(.*\.(gif|png|jpg|css|js)(|\.map))$
      static_files: dist/credit-digital-front/\1
      upload: dist/credit-digital-front/(.*)(|\.map)

    - url: /(.*)
      static_files: dist/credit-digital-front/index.html
      upload: dist/credit-digital-front/index.html

skip_files:
    - e2e/
    - node_modules/
    - src/
    - coverage
    - ^(.*/)?\..*$
    - ^(.*/)?.*\.json$
    - ^(.*/)?.*\.md$
    - ^LICENSE

env_variables:
    NG_ENGINE_BASE_URL: "%ENGINE_BASE_URL%"
    NG_KEYCLOAK_SERVER_URL: "%KEYCLOAK_SERVER_URL%"
    NG_KEYCLOAK_RESOURCE: "%KEYCLOAK_RESOURCE%"
    NG_KEYCLOAK_REALM: "%KEYCLOAK_REALM%"
    NG_KEYCLOAK_REDIRECT_URL: "%KEYCLOAK_REDIRECT_URL%"

